// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addedprofilepicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedprofilepicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201611271611409_Added profile picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
