// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DayEntryLoad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DayEntryLoad));
        
        string IMigrationMetadata.Id
        {
            get { return "201612142301188_DayEntryLoad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
